services :

  grepp-web:
    container_name: grepp-web
    image: grepp-web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net_1

  grepp-db:
    image: mysql
    container_name: grepp-db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=grepp_app_1
      - MYSQL_PASSWORD=grepp_app_1!
      - MYSQL_DATABASE=grepp_exp_db
    networks:
      - net_1

  grepp-app:
    image: grepp-app:0.2
#    image: ghcr.io/silver-eunjoo/2025_grepp_infra_back:sha-fd39e0c
    container_name: grepp-app
    ports:
      - "8080:8080"
    networks:
      - net_1
    depends_on:
      - grepp-db # 서비스 이름 기재하기

networks:
  net_1:
    name: net_1
    driver: bridge
