name : Grepp Sample Backend Service Release

on:
  push:
     branches:
       - main

jobs:

  tagging:
    name: 태깅 및 릴리즈
    runs-on: ubuntu-latest

    steps :
      - uses : actions/checkout@v4

      - name: versioning and tagging
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: releasing
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_version }}
          name: ${{ steps.tag_version.outputs.new_version }}
          body: ${{ steps.tag_version.outputs.changelog }}


  build-image:
    name: 도커 이미지 빌드
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

      - name: Check out Repository
        uses : actions/checkout@v4
